

import {Poppins } from "next/font/google";

import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Poppins({ subsets: ["latin"], weight:[ "400","700"] });

import Header from "../components/Header";
import Footer from "../components/Footer";
// export const metadata = {
//   title: "Ai-Mecca Touring",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();
  return (
    <html lang={locale} className="m-0 p-0 scroll-smooth " suppressHydrationWarning>
      <body className={`${inter.className} relative   w-full min-h-screen  `}>
        <NextIntlClientProvider messages={messages}>
            <Header />
          {children}
       <div className="fixed bottom-0 w-full">
        <Footer /></div>   
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
